os:
- linux
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install --upgrade pip setuptools
- pip install tox-travis
- python setup.py install
script: tox
deploy:
  provider: pypi
  user: tbd
  password:
    secure: "tbd"
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: useblocks/groundwork-spreadsheets
